In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

In [ ]:
data = pd.read_csv(r'C:\Users\Hilton\Documents\GitHub\Data_Science\Advanced_Statistical_Methods\Multiple_Linear_Regression_with_sklearn\1.02.+Multiple+linear+regression.csv')

In [3]:
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [4]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

## Creating the Multiple Regression

In [21]:
#Declaring Variables
y = data['GPA']
x = data[['SAT','Rand 1,2,3']]

In [22]:
#Regression itself
reg = LinearRegression()
reg.fit(x,y)
reg.get_params()

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'normalize': False,
 'positive': False}

In [23]:
#Displays coefficients of the SAT and Rand 1,2,3. In the order we fed them
reg.coef_

array([ 0.00165354, -0.00826982])

In [24]:
reg.intercept_

0.29603261264909353

## Calculating the R-Squared

In [25]:
reg.score(x,y)

0.4066811952814282

#However we want the Adjusted R-squared as it steps on the R-squared
#and adjusts for the number of variables included in the model
### Formular for Adjusted R^2

$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

In [26]:
#Where n=number of observations(84)
#& p=number of predictors(2)
x.shape

(84, 2)

In [27]:
r2 = reg.score(x,y)

n=x.shape[0]
p=x.shape[1]

adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2


0.39203134825134

In [12]:
#Adjusted R^2 < R^2, therefore one or more predictors
#have little or no explanatory power

In [13]:
#How do we identify and remove one of these predictors which bring no value?
#This is called Feature selection
#Feature selection simplifies models, improves speed and prevents
#a series of unwanted issues arising from having too many features

In [14]:
#We use the F-regression which creates simple linear regressions of each feature
#and the dependent vaiable
#e.g GPA<----SAT & GPA<----Rand 1,2,3

#Note that for a simple linear regression
#the p-value of F-stat is equivalent to the p-value of the only indep. variable

## Feature Selection

In [28]:
from sklearn.feature_selection import f_regression

In [30]:
f_regression(x,y)
#First array contains F-Statistics for each of the regressions
#Second array contains coressponding p-values
#We are interested in only the p-values

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [31]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [32]:
#Rounding to 3 decimals 
p_values.round(3)
#Hence p-value of SAT is 0.0000 and Rand 1,2,3 is 0.676
#It is now easy to see that the p-value of Rand 1,2,3 is >0.05 and therefore
#Rand 1,2,3 is useless

array([0.   , 0.676])

In [19]:
#It is important to note that these p-values are reached from simple
#linear models and they do not reflect the interconnection of the features
#in our multiple linear regression

## Creating a Summary Table

In [38]:
reg_summary= pd.DataFrame(data=x.columns.values, columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

## Adding Columns to our summary table

In [43]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['p-values'] = p_values.round(3)


In [44]:
reg_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

In [ ]:
# p-values are one of the best ways determine if a variable is redundant
#however they do not provide information on how useful the variable is